[package]
name = "kl-code"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kl-core.workspace = true
anyhow.workspace = true
libsql.workspace = true
tokio.workspace = true
serde.workspace = true
chrono.workspace = true
tracing.workspace = true
zerocopy.workspace = true
